import React, { useState, useEffect, useCallback } from 'react';
import { getAllPrompts } from '../services/supabaseService';
import type { SavedPrompt } from '../types';
import { GalleryPromptCard } from '../App';
import { RssIcon } from './icons';

type PageProps = {
  onBack: () => void;
};

const GallerySkeleton: React.FC<{ count?: number }> = ({ count = 12 }) => (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {Array.from({ length: count }).map((_, i) => (
            <div key={i} className="bg-gray-900/50 border border-green-400/10 rounded-sm p-4 h-[180px] animate-pulse">
                <div className="h-3 bg-gray-700/50 rounded w-5/6 mb-2"></div>
                <div className="h-3 bg-gray-700/50 rounded w-full mb-2"></div>
                <div className="h-3 bg-gray-700/50 rounded w-3/4"></div>
                <div className="absolute bottom-4 left-4 right-4 h-3 bg-gray-700/50 rounded w-1/3"></div>
            </div>
        ))}
    </div>
);

const PROMPTS_PER_PAGE = 12;

export const GalleryPage: React.FC<PageProps> = ({ onBack }) => {
    const [prompts, setPrompts] = useState<SavedPrompt[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isLoadingMore, setIsLoadingMore] = useState(false);
    const [page, setPage] = useState(1);
    const [hasMore, setHasMore] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const fetchPrompts = useCallback(async (pageNum: number) => {
      if (pageNum === 1) setIsLoading(true);
      else setIsLoadingMore(true);
      
      setError(null);

      try {
        const { prompts: newPrompts, hasMore: newHasMore } = await getAllPrompts(pageNum, PROMPTS_PER_PAGE);
        setPrompts(prev => pageNum === 1 ? newPrompts : [...prev, ...newPrompts]);
        setHasMore(newHasMore);
      } catch (err) {
        setError("Could not load prompts. Please try again later.");
      } finally {
        if (pageNum === 1) setIsLoading(false);
        else setIsLoadingMore(false);
      }
    }, []);

    useEffect(() => {
        fetchPrompts(1);
    }, [fetchPrompts]);

    const handleLoadMore = () => {
        const nextPage = page + 1;
        setPage(nextPage);
        fetchPrompts(nextPage);
    };

    return (
        <div className="max-w-7xl mx-auto animate-fade-in">
            <button onClick={onBack} className="mb-8 text-green-400 hover:text-green-300 transition-colors font-bold">[ &lt; Back to Generator ]</button>
            <div className="text-center mb-12">
                <h1 className="text-4xl md:text-5xl font-bold text-slate-100 tracking-wide">Community Gallery</h1>
                <p className="mt-4 max-w-2xl mx-auto text-lg text-slate-400">
                    Browse the full collection of prompts generated by our creative community.
                </p>
            </div>

            {isLoading ? (
                <GallerySkeleton />
            ) : error ? (
                <div className="text-center text-red-400 p-8 bg-red-900/20 border border-red-500/30 rounded-sm">
                    {error}
                </div>
            ) : prompts.length > 0 ? (
                <>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                        {prompts.map(p => <GalleryPromptCard key={`${p.id}-${p.created_at}`} prompt={p} />)}
                    </div>

                    {hasMore && (
                        <div className="mt-12 text-center">
                             <button
                                onClick={handleLoadMore}
                                disabled={isLoadingMore}
                                className="w-48 flex items-center justify-center mx-auto px-6 py-3 border border-green-400/20 text-base font-bold rounded-sm text-green-300 bg-gray-800/50 hover:bg-gray-700/50 disabled:bg-slate-700 disabled:text-slate-400 disabled:cursor-not-allowed transition-all duration-300"
                            >
                                {isLoadingMore ? (
                                    <>
                                        <svg className="animate-spin -ml-1 mr-3 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                        Loading...
                                    </>
                                ) : (
                                    'Load More'
                                )}
                            </button>
                        </div>
                    )}
                </>
            ) : (
                <div className="text-center text-slate-500 border-2 border-dashed border-slate-800 rounded-sm p-12">
                    <RssIcon className="mx-auto h-12 w-12 text-slate-600" />
                    <h3 className="mt-2 text-lg font-medium text-slate-400">The Gallery is Still Empty</h3>
                    <p className="mt-1 text-sm">Be the first to generate and share a prompt to see it here!</p>
                </div>
            )}
        </div>
    );
};